llm:
  use: openai, siliconflow
  openai:
    - api_key: "sk-your-openai-key"
      api_base: "https://api.openai.com/v1"
      model: "gpt-4o-mini"
      rate_limit: 20
    
  siliconflow:
    - api_key: "sk-xxx"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "deepseek-ai/DeepSeek-V2.5"
      rate_limit: 20
    
    - api_key: "sk-xxx"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "deepseek-ai/DeepSeek-V2.5"
      rate_limit: 20
    
   